server.port=8082
spring.application.name=admin-server
spring.security.user.name=admin
spring.security.user.password=password
spring.boot.admin.client.instance.metadata.user.name=${spring.security.user.name}
spring.boot.admin.client.instance.metadata.user.password=${spring.security.user.password}
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
