spring.application.name=NextSkill-webapp
server.port=8080

spring.config.import=classpath:project.properties

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,metrics,beans
management.endpoint.health.show-details=always

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=activemquser
spring.activemq.password=activemqpassword

spring.boot.admin.client.url=http://localhost:8081
spring.boot.admin.client.instance.name=webapp-service
