spring.application.name=NextSkill-webapp
# gRPC client configuration
grpc.client.notification-service.address=static://localhost:9091
grpc.client.notification-service.negotiationType=PLAINTEXT
spring.config.import=optional:configserver:http://localhost:8888,classpath:project.properties
