spring.application.name=NextSkill

# gRPC client configuration
grpc.client.notification-service.address=static://localhost:9091
grpc.client.notification-service.negotiationType=PLAINTEXT-webapp
spring.config.import=optional:configserver:http://localhost:8888,classpath:project.properties
