spring.application.name=NextSkill-config-server
server.port=8888

spring.config.import=classpath:project.properties

spring.cloud.config.server.git.uri=git-url
spring.cloud.config.server.git.private-key=private-key
spring.cloud.config.server.git.clone-on-start=true

# TODO: add security, encryption, add actuator/admin, add compose/k8s, add check config-server is up before starting other services
#spring.security.user.name=config-server-user
#spring.security.user.password=config-server-password
