version: "3.8"
name: next-skill
services:
  postgres:
    image: postgres:13.4
    container_name: next-skill-database
    environment:
      POSTGRES_DB: nextskilldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  activemq:
    image: apache/activemq-classic:5.18.3
    container_name: next-skill-message-broker
    environment:
      ACTIVEMQ_USERNAME: activemquser
      ACTIVEMQ_PASSWORD: activemqpassword
    ports:
      - "61616:61616" # OpenWire protocol port
      - "8161:8161"   # ActiveMQ web console port
    volumes:
      - activemq-data:/opt/activemq/data

volumes:
  database:
  activemq-data:
