spring.application.name=NextSkill-email-service
spring.config.import=optional:configserver:http://localhost:8888,classpath:project.properties

# gRPC server configuration
grpc.server.port=9091
grpc.server.address=0.0.0.0
